name: Build CI

on:
  push:
    branches: [ master, develop ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build.sh
        run: ./build.sh
