name: Build CI

env:
  PROJECT_LABEL: alpha

on:
  push:
    branches: [ master, develop ]

  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build.sh --target=build
        run: ./build.sh --target=build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build.sh --target=test
        run: ./build.sh --target=test

      - name: Install Codecov Uploader
        if: ${{ github.event_name == 'push' }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov

      - name: Upload Codecov
        if: ${{ github.event_name == 'push' }}
        run: ./codecov -Z -F unittests

  deploy-develop:
    needs: test
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add NuGet Source
        run: dotnet nuget add source --username e5r --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/e5r/index.json"

      - name: build.sh --target=dist
        run: ./build.sh --target=dist --version-suffix=${PROJECT_LABEL}-$(printf '%04d' ${{ github.run_number }})

      - name: Push NuGet Packages
        run: dotnet nuget push "dist/*.nupkg"  --source "github"

  deploy-master:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build.sh --target=dist
        run: ./build.sh --target=dist

      - name: Push NuGet Packages
        run: dotnet nuget push "dist/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json

